public class helloWorld {

	 public static final string ACC_NAME = 'Test'; // constant
	public final string accName = 'Test 2' ;// final     
    
   
    
    //public static string Name ='test';
    
    
    public helloWorld(string ACC_NAME){
        
       //ACC_NAME = 'Test';
        
       // this.ACC_NAME = ACC_NAME;
        
        //system.debug('consructor'+accName);
        
    }
    
     
    
    public  void add(){
        
        //accName = 'raja svn';
         //system.debug('method'+accName);
        
    }
    
    

}